//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public string UserName { get; set; }
        public string UserLoginName { get; set; }
        public Nullable<int> IsVip { get; set; }
        public Nullable<int> IsOnLine { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrUserName { get; set; }
        public string CrUserRealName { get; set; }
        public Nullable<System.DateTime> MoDate { get; set; }
        public string MoUserRealName { get; set; }
        public string MoUserName { get; set; }
        public Nullable<int> Age { get; set; }
        public string UserPsd { get; set; }
        public Nullable<int> IsUseful { get; set; }
        public string UserRealName { get; set; }
        public string UserMail { get; set; }
        public int Id { get; set; }
    }
}
