//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMSG
    {
        public int userid { get; set; }
        public string password { get; set; }
        public string zt { get; set; }
        public string username { get; set; }
        public string workcode { get; set; }
        public string Email { get; set; }
        public string phoneNumber { get; set; }
        public string address { get; set; }
        public string departmentid { get; set; }
        public string company { get; set; }
        public string login { get; set; }
    }
}
